In [1]:
years = list(range(1991, 2022))
print(years, end=" ")

[1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]

In [2]:
url_start = "https://www.basketball-reference.com/awards/awards_{}.html"

In [4]:
import requests
import time

for year in years:
    url = url_start.format(year)
    data = requests.get(url)

    with open("MVP/{}.html".format(year), "w+", encoding="utf-8") as f:
        time.sleep(3)
        f.write(data.text)

In [5]:
from bs4 import BeautifulSoup
with open("MVP/1991.html", encoding="utf-8") as f:
    page = f.read()
soup = BeautifulSoup(page, "html.parser")

In [6]:
soup.find("tr", class_="over_header").decompose()
print("Header row removed successfully")

mvp_table = soup.find(id="mvp")

Header row removed successfully

In [7]:
import pandas as pd
mvp_1991 = pd.read_html(str(mvp_table))[0]
mvp_1991

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,37.0,31.5,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321
1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,37.1,19.4,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251
2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,37.7,25.6,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264
3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,37.3,27.6,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258
4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,40.3,29.0,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225
5,6,Clyde Drexler,28,POR,1.0,75.0,960,0.078,82,34.8,21.5,6.7,6.0,1.8,0.7,0.482,0.319,0.794,12.4,0.209
6,7,Kevin Johnson,24,PHO,0.0,32.0,960,0.033,77,36.0,22.2,3.5,10.1,2.1,0.1,0.516,0.205,0.843,12.7,0.220
7,8,Dominique Wilkins,31,ATL,0.0,29.0,960,0.030,81,38.0,25.9,9.0,3.3,1.5,0.8,0.470,0.341,0.829,11.4,0.177
8,9T,Larry Bird,34,BOS,0.0,25.0,960,0.026,60,38.0,19.4,8.5,7.2,1.8,1.0,0.454,0.389,0.891,6.6,0.140
9,9T,Terry Porter,27,POR,0.0,25.0,960,0.026,81,32.9,17.0,3.5,8.0,2.0,0.1,0.515,0.415,0.823,13.0,0.235
10,11,Patrick Ewing,28,NYK,0.0,20.0,960,0.021,81,38.3,26.6,11.2,3.0,1.0,3.2,0.514,0.000,0.745,10.0,0.155
11,12,John Stockton,28,UTA,0.0,15.0,960,0.016,82,37.8,17.2,2.9,14.2,2.9,0.2,0.507,0.345,0.836,14.0,0.217
12,13,Isiah Thomas,29,DET,0.0,11.0,960,0.011,48,34.5,16.2,3.3,9.3,1.6,0.2,0.435,0.292,0.782,3.4,0.098
13,14,Robert Parish,37,BOS,0.0,10.0,960,0.010,81,30.1,14.9,10.6,0.8,0.8,1.3,0.598,0.000,0.767,10.0,0.198
14,15,Joe Dumars,27,DET,0.0,8.0,960,0.008,80,38.1,20.4,2.3,5.5,1.1,0.1,0.481,0.311,0.890,9.9,0.155
15,16,Bernard King,34,WSB,0.0,7.0,960,0.007,64,37.5,28.4,5.0,4.6,0.9,0.3,0.472,0.216,0.790,3.5,0.070
16,17,Kenny Smith,25,HOU,0.0,5.0,960,0.005,78,34.6,17.7,2.1,7.1,1.4,0.1,0.520,0.363,0.844,9.0,0.161
17,18,Hakeem Olajuwon,28,HOU,0.0,4.0,960,0.004,56,36.8,21.2,13.8,2.3,2.2,3.9,0.508,0.000,0.769,8.6,0.201
18,19T,Tim Hardaway,24,GSW,0.0,1.0,960,0.001,82,39.2,22.9,4.0,9.7,2.6,0.1,0.476,0.385,0.803,9.9,0.148
19,19T,Kevin McHale,33,BOS,0.0,1.0,960,0.001,68,30.4,18.4,7.1,1.9,0.4,2.1,0.553,0.405,0.829,7.9,0.182

In [9]:
all_dfs = []
for year in years:
    with open("MVP/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()

        soup = BeautifulSoup(page, "html.parser")
        soup.find("tr", class_="over_header").decompose()
        mvp_table = soup.find(id="mvp")
        mvp = pd.read_html(str(mvp_table))[0]
        mvp["Year"] = year
        all_dfs.append(mvp)

In [10]:
mvps = pd.concat(all_dfs)
pd.pandas.set_option('display.max_columns', None)
mvps.sample(5)

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
4,5,Kobe Bryant,23,LAL,1.0,98.0,1260,0.078,80,38.3,25.2,5.5,5.5,1.5,0.4,0.469,0.250,0.829,12.7,0.199,2002
2,3,Anthony Davis,24,NOP,0.0,445.0,1010,0.441,75,36.4,28.1,11.1,2.3,1.5,2.6,0.534,0.340,0.828,13.7,0.241,2018
7,8,Shawn Kemp,26,SEA,0.0,73.0,1130,0.065,79,33.3,19.6,11.4,2.2,1.2,1.6,0.561,0.417,0.742,11.2,0.205,1996
5,6,Clyde Drexler,28,POR,1.0,75.0,960,0.078,82,34.8,21.5,6.7,6.0,1.8,0.7,0.482,0.319,0.794,12.4,0.209,1991
8,9,Steve Nash,33,PHO,0.0,18.0,1260,0.014,81,34.3,16.9,3.5,11.1,0.7,0.1,0.504,0.470,0.906,10.5,0.181,2008

In [11]:
mvps.to_csv("mvps.csv")

In [12]:
player_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"
url = player_stats_url.format(1991)
data = requests.get(url)
with open("Players/1991.html", "w+", encoding="utf-8") as f:
    f.write(data.text)

In [13]:
from selenium import webdriver

driver = webdriver.Chrome(executable_path="PATH TO CHROMEDRIVER EXECUTABLE")

C:\Users\09har\AppData\Local\Temp\ipykernel_20532\4169496178.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path="PATH TO CHROMEDRIVER EXECUTABLE")

In [14]:
import time
year = 1991
url = player_stats_url.format(year)
driver.get(url)
driver.execute_script("window.scrollTo(1, 1000)")
time.sleep(2)

html = driver.page_source

In [15]:
with open("Players/{}.html".format(year), "w+", encoding="utf-8") as f:
    f.write(html)

In [16]:
for year in years:
    url = player_stats_url.format(year)
    driver.get(url)
    driver.execute_script("window.scrollTo(1, 1000)")
    time.sleep(2)
    html = driver.page_source
    with open("Players/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(html)

In [18]:
player_df = []
for year in years:
    with open("Players/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    soup = BeautifulSoup(page, "html.parser")
    soup.find("tr", class_="thead").decompose()
    player_table = soup.find(id="per_game_stats")
    player = pd.read_html(str(player_table))[0]
    player["Year"] = year
    player_df.append(player)

In [19]:
players = pd.concat(player_df)
pd.pandas.set_option('display.max_columns', None)
players.sample(5)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
220,187,Larry Hughes,SG,23,GSW,73,56,28.1,4.7,11.1,.423,0.2,1.3,.194,4.5,9.8,.453,.435,2.6,3.5,.737,1.1,2.2,3.4,4.3,1.5,0.3,2.3,2.1,12.3,2002
116,83,Speedy Claxton,PG,26,TOT,62,47,30.1,4.1,9.9,.421,0.2,1.0,.180,4.0,8.9,.447,.430,3.0,4.1,.736,0.6,2.4,3.0,6.0,1.8,0.1,1.9,3.0,11.5,2005
105,80,Josh Childress,SF,22,ATL,74,10,30.4,3.8,6.8,.552,0.4,0.9,.492,3.3,5.9,.560,.583,2.1,2.7,.766,1.8,3.4,5.2,1.8,1.2,0.5,1.4,2.5,10.0,2006
172,146,Geert Hammink,C,25,ORL,1,0,7.0,1.0,3.0,.333,0.0,0.0,NaN,1.0,3.0,.333,.333,2.0,2.0,1.000,0.0,2.0,2.0,1.0,0.0,0.0,0.0,1.0,4.0,1995
594,418,Gerald Wallace,SF,28,CHA,48,48,39.0,5.3,12.1,.433,0.7,2.2,.330,4.5,9.9,.456,.463,4.4,5.9,.739,1.5,6.7,8.2,2.4,1.2,1.0,2.1,2.5,15.6,2011

In [20]:
players.to_csv("player_stats.csv")

In [21]:
team_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"
for year in years:
    url = team_stats_url.format(year)
    data = requests.get(url)

    with open("Team/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)

In [22]:
dfs = []
for year in years:
    with open("Team/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr', class_="thead").decompose()

    e_table = soup.find_all(id="divs_standings_E")[0]
    e_df = pd.read_html(str(e_table))[0]
    e_df["Year"] = year
    e_df["Team"] = e_df["Eastern Conference"]
    del e_df["Eastern Conference"]
    dfs.append(e_df)

    w_table = soup.find_all(id="divs_standings_W")[0]
    w_df = pd.read_html(str(w_table))[0]
    w_df["Year"] = year
    w_df["Team"] = w_df["Western Conference"]
    del w_df["Western Conference"]
    dfs.append(w_df)

In [23]:
teams = pd.concat(dfs)

In [24]:
teams

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team
0   56  26  .683     —  111.5  105.7   5.22  1991       Boston Celtics*
1   44  38  .537  12.0  105.4  105.6  -0.39  1991   Philadelphia 76ers*
2   39  43  .476  17.0  103.1  103.3  -0.43  1991      New York Knicks*
3   30  52  .366  26.0  101.4  106.4  -4.84  1991    Washington Bullets
4   26  56  .317  30.0  102.9  107.5  -4.53  1991       New Jersey Nets
..  ..  ..   ...   ...    ...    ...    ...   ...                   ...
13  42  30  .583     —  112.4  110.2   2.26  2021     Dallas Mavericks*
14  38  34  .528   4.0  113.3  112.3   1.07  2021    Memphis Grizzlies*
15  33  39  .458   9.0  111.1  112.8  -1.58  2021     San Antonio Spurs
16  31  41  .431  11.0  114.6  114.9  -0.20  2021  New Orleans Pelicans
17  17  55  .236  25.0  108.8  116.7  -7.50  2021       Houston Rockets

[1033 rows x 9 columns]

In [25]:
teams.head()

    W   L  W/L%    GB   PS/G   PA/G    SRS  Year                 Team
0  56  26  .683     —  111.5  105.7   5.22  1991      Boston Celtics*
1  44  38  .537  12.0  105.4  105.6  -0.39  1991  Philadelphia 76ers*
2  39  43  .476  17.0  103.1  103.3  -0.43  1991     New York Knicks*
3  30  52  .366  26.0  101.4  106.4  -4.84  1991   Washington Bullets
4  26  56  .317  30.0  102.9  107.5  -4.53  1991      New Jersey Nets

In [26]:
teams.tail()

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team
13  42  30  .583     —  112.4  110.2   2.26  2021     Dallas Mavericks*
14  38  34  .528   4.0  113.3  112.3   1.07  2021    Memphis Grizzlies*
15  33  39  .458   9.0  111.1  112.8  -1.58  2021     San Antonio Spurs
16  31  41  .431  11.0  114.6  114.9  -0.20  2021  New Orleans Pelicans
17  17  55  .236  25.0  108.8  116.7  -7.50  2021       Houston Rockets

In [27]:
teams.to_csv("teams.csv")